### ISSUE TITLE
Extension 'SimpleLocalize' not compatible with VS Code version 1.94.2

### ISSUE THREAD

**Issue by jmargotin-ma** [simplelocalize/vscode-simplelocalize-extension#1]
I am unable to install the SimpleLocalize extension (simplelocalize.simplelocalize) due to compatibility issues with my current version of Visual Studio Code (v1.94.2).

### **Steps to Reproduce:**

- Open Visual Studio Code (version 1.94.2).
- Search for the SimpleLocalize extension in the Extensions Marketplace.
- Attempt to install the extension.

**### Expected Behavior:**
The extension should install successfully if compatible with the current version of VS Code.

### **Actual Behavior:**
An error is displayed stating that the extension is not compatible with the current version of Visual Studio Code.

### **Additional Information:**

**VS Code version:** 1.94.2
**OS:** MacOS Sequoia 15.1
**SimpleLocalize extension version:** 1.0.11

**Comment by jpomykala** [comment]
Hey @jmargotin-ma thanks for the report. I've just released version 1.0.12 that requires lower VS Code version (1.94.x) Could you please check if it's okay now? It should be now available in marketplace.

**Comment by jmargotin-ma** [comment]
Hi @jpomykala,

Thank you for the quick fix! I just tested version 1.0.12, and it works perfectly with VS Code 1.94.x. I appreciate the swift update and support.

Cheers
